config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord

    validates :meal_type, :calories, :proteins, :carbohydrates, :fats,  presence: true

    def day
        self.created_at.strftime("%b %e, %Y")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.where("created_at >= ?", Date.today)
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="is-flex is-justify-content-center">
<div class="columns is-centered mb-6 mt-6">
  <div class="column is-half ">
   <% @entries.each do |day, entries| %>
      <h3 class="is-size-4 has-text-wight mb-4 mt-6 has-text-centered">Entries for <%= day%>
      </h3>


      <nav class="level is-mobile">
        <div class="level-item has-text-centered">
            <div>
               <p class="heading">CALORIES</p>
               <p class="title"><%= entries.pluck(:calories).sum %></p> 
            </div>
        </div>
        <div class="level-item has-text-centered">
            <div>
               <p class="heading">PROTEINS</p>
               <p class="title"><%= entries.pluck(:proteins).sum %>g</p>
            </div>
        </div>
        <div class="level-item has-text-centered">
            <div>
               <p class="heading">CARBOHYDRATES</p>
               <p class="title"><%= entries.pluck(:carbohydrates).sum %>g</p>
            </div>
        </div>
        <div class="level-item has-text-centered">
            <div>
               <p class="heading">FATS</p>
               <p class="title"><%= entries.pluck(:fats).sum %>g</p>
            </div>
        </div>
      </nav>

        <% entries.each do |entry| %>
            <%= link_to entry_path(entry) do %>
              <div class="card"> 
                    <div class="card-content">
                      <strong><%= entry.meal_type %></strong><br/>
                      <%= entry.calories %>calories,
                      <%= entry.proteins %>g proteins,
                      <%= entry.carbohydrates%>g carbohydrates,
                      <%= entry.fats%>g fats
                    </div>
                </div>
            <%end%>
        <%end%>
    <%end%>
  </div>
 </div>
</div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
 <div class="card">
  <header class="card-header">
   <p class="card-header-title"><%= entry.meal_type %></p>
  </header>

  <div class="card-content">
   <div class="content">

    <p><span class="has-text-weight-bold"><%= entry.calories %></span> calories</p>
    <p><span class="has-text-weight-bold"><%= entry.proteins %></span> gram of protein</p>
    <p><span class="has-text-weight-bold"><%= entry.carbohydrates %></span> gram of carbohydrates</p>
    <p><span class="has-text-weight-bold"><%= entry.fats %></span>gram of fats</p>
    <p class="italic">Logged <%= time_ago_in_words(entry.created_at)%> ago</p>

   </div>
  </div>
   
 </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
   <div class="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>
       <div class="message-body">
        <ul>
          <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
          <% end %>
        </ul>
    </div>
   </div>
  <% end %>

  <div>
    <%= form.label :meal_type, style: "display: block",class:"label" %>
    <%= form.text_field :meal_type,class:"input" %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block",class:"label" %>
    <%= form.number_field :calories ,class:"input"%>
  </div>

  <div>
    <%= form.label :proteins, style: "display: block",class:"label" %>
    <%= form.number_field :proteins ,class:"input"%>
  </div>

  <div>
    <%= form.label :carbohydrates, style: "display: block",class:"label" %>
    <%= form.number_field :carbohydrates ,class:"input"%>
  </div>

  <div>
    <%= form.label :fats, style: "display: block",class:"label" %>
    <%= form.number_field :fats ,class:"input"%>
  </div>

  <div class="is-flex  is-justify-content-center mt-5">
    <%= form.submit class:"button is-success" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="is-flex is-justify-content-center">
  <div class="columns is-centered mt-6">
    <div class="column is-one-third">
      <h1 class="is-size-2 has-text-weight-bold mb-3">Editing entry</h1>
      <%= render "form", entry: @entry %>
    </div>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Food Log &ndash; <%= DateTime.now.to_formatted_s(:long_ordinal) %>
  <%end%>

<div class="columns mt-6 ">
<div class="is-flex is-flex-wrap-wrap is-justify-content-center"
  <div id="entries">
    <% @entries.each do |entry| %>
     <div class="column is-one-quarter">
      <%= render entry %>
        <div class="card">
          <div class="card-footer">
           <%= link_to "Show this entry", entry, class:"card-footer-item button is-success mt-1 is-light" %>
          </div>
        </div>
     </div> 
    <% end %>
    </div>
  </div>


</div>
<div class="columns is-centered mt-6">
<%= link_to "View all Entries", archives_index_path, class:"button is-link is-outlined is-cenntered mb-5"%>
</div>

app/views/entries/new.html.erb
</div>

  <div class="columns is-centered mt-6">
    <div class="column is-one-third">
      <h1 class="is-size-2 has-text-weight-bold mb-3">New Entry</h1>
      <%= render "form", entry: @entry %>
    </div>
  </div>
</div>
<div>

app/views/entries/show.html.erb
<div class="columns mt-6 ">
  <div class="is-flex is-justify-content-center"
    <div class="columns mt-6 ">
      <div class="column is-one-quarter">
       <%= render @entry %>
        <div class="card">
         <div class="card-footer">
         <%= link_to "Edit", edit_entry_path(@entry),class:"card-footer-item button is-warning mt-1 is-light" %>
         <%= link_to "Back", entries_path,class:"card-footer-item button is-success mt-1 is-light " %>
         <%= button_to "Destroy", @entry, method: :delete,class:"card-footer-item button is-danger mt-1 is-light" %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <script src="https://kit.fontawesome.com/19cea4317e.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
  <%= render "shared/header"%>
  <% if notice.present?%>
  <div class="notification is-link is-light"><%= notice %></div>
  <%end%>
  <% if alert.present?%>
  <div class="notification is-danger is-light"><%= alert %></div>
  <%end%>
  <div class="container "
    <%= yield %>
  </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-primary is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
         <%= link_to root_path, class:"navbar-item" do %>
          <i class="fa-solid fa-utensils fa-bounce fs-1"></i>
          <span class="title is-3">CALORIES COUNT</span>
         <%end%>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
           <span class="navbar-item">
            <%= link_to "New entry", new_entry_path, class:"button is-primary is-inverted" %> 
           </span>   
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
       <% if content_for(:title) %>
       <%= yield :title %>
       <% else %>
       Food Log
       <%end%>
      </p>
    </div>
  </div>

  <!-- Hero footer: will stick at the bottom -->
 
</section>